 // Source code is unavailable, and was generated by the Fernflower decompiler.
import java.util.Iterator;
import java.util.Vector;

public class Catalog {
   private Vector products = new Vector();

   public void addProduct(Product var1) {
      this.products.add(var1);
   }

   public Iterator getProductsIterator() {
      return this.products.iterator();
   }

   public Product getProduct(String var1) {
      Iterator var2 = this.getProductsIterator();

      Product var3;
      do {
         if (!var2.hasNext()) {
            return null;
         }

         var3 = (Product)var2.next();
      } while(!var3.getCode().equals(var1));

      return var3;
   }

   public int getNumberOfProducts() {
      return this.products.size();
   }
}
